---
- name: Create domains
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item }}"
    state: present
  with_items:
    - "{{ domains }}"
  vars:
    domains: "{{ lookup('file', 'vars/domains.yml') }}"