---
- name: Install Apache Docker Container with PHP 7.2 and Nginx with GeoIP support
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      register: docker_install

    - name: Install Python Pip
      apt:
        name: python3-pip
        state: present
      register: python_pip_install

    - name: Install Docker-py
      pip:
        name: docker-py
        state: present

    - name: Pull Apache-PHP 7.2 Docker Image
      docker_image:
        name: php:7.2-apache
        source: pull
        state: present

    - name: Pull Nginx Docker Image
      docker_image:
        name: admintuts/nginx:1.21.4-rtmp-geoip2-alpine
        source: pull
        state: present

    - name: Create custom Docker network
      command: docker network create --subnet=10.0.0.0/24 custom_network

    - name: Create folder structure
      file:
        path: /srv
        state: directory
        mode: 0755
      register: folder_structure

    - name: Create Nginx config folder
      file:
        path: "{{ folder_structure.path }}/nginx/conf"
        state: directory
        mode: 0755

    - name: Create Nginx logs folder
      file:
        path: "{{ folder_structure.path }}/nginx/logs"
        state: directory
        mode: 0777

    - name: Create Apache01 config folder
      file:
        path: "{{ folder_structure.path }}/apache/conf/apache01"
        state: directory
        mode: 0755

    - name: Create Apache02 config folder
      file:
        path: "{{ folder_structure.path }}/apache/conf/apache02"
        state: directory
        mode: 0755

    - name: Create Apache logs folder
      file:
        path: "{{ folder_structure.path }}/apache/logs"
        state: directory
        mode: 0755

    - name: Create MySQL config folder
      file:
        path: "{{ folder_structure.path }}/mysql/conf"
        state: directory
        mode: 0755

    - name: Create MySQL logs folder
      file:
        path: "{{ folder_structure.path }}/mysql/logs"
        state: directory
        mode: 0755

    - name: Create content folder
      file:
        path: "{{ folder_structure.path }}/www/html"
        state: directory
        mode: 0755

    - name: Create first.tst domain
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 first.tst"
        state: present

    - name: Create second.tst domain
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 second.tst"
        state: present

    - name: Create first.tst folder
      file:
        path: "{{ folder_structure.path }}/www/html/first"
        state: directory
        mode: 0755

    - name: Create second.tst folder
      file:
        path: "{{ folder_structure.path }}/www/html/second"
        state: directory
        mode: 0755

    - name: Copy index.php to first.tst folder
      copy:
        src: index.php
        dest: "{{ folder_structure.path }}/www/html/first"

    - name: Copy index.php to second.tst folder
      copy:
        src: index.php
        dest: "{{ folder_structure.path }}/www/html/second"

    - name: Create Nginx Container
      docker_container:
        name: nginx
        image: admintuts/nginx:1.21.4-rtmp-geoip2-alpine
        state: started
        restart_policy: always
        ports:
          - "80:80"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.2
        volumes:
          - "{{ folder_structure.path }}/nginx/conf:/etc/nginx/conf"
          - "{{ folder_structure.path }}/nginx/logs:/var/log/nginx"

    - name: Create Apache-PHP 7.2 Container-01
      docker_container:
        name: apache01
        image: php:7.2-apache
        state: started
        restart_policy: always
        ports:
          - "8081:8081"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.3
        volumes:
          - "{{ folder_structure.path }}/apache/conf/apache01:/etc/apache2"
          - "{{ folder_structure.path }}/apache/logs:/var/log/apache2"
          - "{{ folder_structure.path }}/www/html:/var/www/html"

    - name: Create Apache-PHP 7.2 Container-02
      docker_container:
        name: apache02
        image: php:7.2-apache
        state: started
        restart_policy: always
        ports:
          - "8082:8082"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.4
        volumes:
          - "{{ folder_structure.path }}/apache/conf/apache02:/etc/apache2"
          - "{{ folder_structure.path }}/apache/logs:/var/log/apache2"
          - "{{ folder_structure.path }}/www/html:/var/www/html"

    - name: Copying Nginx-proxy config
      copy:
        src: nginx.conf
        dest: "{{ folder_structure.path }}/nginx/conf/nginx-proxy.conf"

    - name: Copying Apache01 config
      copy:
        src: apache01.conf
        dest: "{{ folder_structure.path }}/apache/conf/apache01/apache2.conf"

    - name: Copying Apache02 config
      copy:
        src: apache01.conf
        dest: "{{ folder_structure.path }}/apache/conf/apache02/apache2.conf"

    - name: Restart containers
      command: docker restart nginx apache1 apache2