---
- name: Install Apache Docker Container with PHP 7.2 and Nginx with GeoIP support
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      register: docker_install

    - name: Install Python Pip
      apt:
        name: python3-pip
        state: present
      register: python_pip_install

    - name: Install Docker-py
      pip:
        name: docker-py
        state: present

    - name: Pull Apache-PHP 7.2 Docker Image
      docker_image:
        name: php:7.2-apache
        source: pull
        state: present

    - name: Pull Nginx Docker Image
      docker_image:
        name: admintuts/nginx:1.21.4-rtmp-geoip2-alpine
        source: pull
        state: present

    - name: Create custom Docker network
      command: docker network create --subnet=10.0.0.0/24 custom_network

    - name: Create folder structure
      file:
        path: /srv
        state: directory
        mode: 0755
      register: folder_structure

    - name: Create Nginx config folder
      file:
        path: "{{ folder_structure.path }}/nginx/conf"
        state: directory
        mode: 0755

    - name: Create Nginx logs folder
      file:
        path: "{{ folder_structure.path }}/nginx/logs"
        state: directory
        mode: 0755

    - name: Create Apache config folder
      file:
        path: "{{ folder_structure.path }}/apache/conf"
        state: directory
        mode: 0755

    - name: Create Apache logs folder
      file:
        path: "{{ folder_structure.path }}/apache/logs"
        state: directory
        mode: 0755

    - name: Create MySQL config folder
      file:
        path: "{{ folder_structure.path }}/mysql/conf"
        state: directory
        mode: 0755

    - name: Create MySQL logs folder
      file:
        path: "{{ folder_structure.path }}/mysql/logs"
        state: directory
        mode: 0755

    - name: Create content folder
      file:
        path: "{{ folder_structure.path }}/www/html"
        state: directory
        mode: 0755

    - name: Create first.tst domain
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 first.tst"
        state: present

    - name: Create second.tst domain
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 second.tst"
        state: present

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: "{{ folder_structure.path }}/nginx/conf/nginx.conf"

    - name: Configure Apache1
      template:
        src: apache1.conf.j2
        dest: "{{ folder_structure.path }}/apache/conf/apache1.conf"

    - name: Configure Apache2
      template:
        src: apache2.conf.j2
        dest: "{{ folder_structure.path }}/apache/conf/apache2.conf"

    - name: Create Nginx Container
      docker_container:
        name: nginx
        image: admintuts/nginx:1.21.4-rtmp-geoip2-alpine
        state: started
        ports:
          - "8080:80"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.2

    - name: Create Apache-PHP 7.2 Container-1
      docker_container:
        name: apache1
        image: php:7.2-apache
        state: started
        ports:
          - "8081:8081"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.3

    - name: Create Apache-PHP 7.2 Container-2
      docker_container:
        name: apache2
        image: php:7.2-apache
        state: started
        ports:
          - "8082:8082"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.4

    - name: Create Nginx Container
      docker_container:
        name: nginx
        image: admintuts/nginx:1.21.4-rtmp-geoip2-alpine
        state: started
        ports:
          - "80:80"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.2

    - name: Create Apache-PHP 7.2 Container-1
      docker_container:
        name: apache1
        image: php:7.2-apache
        state: started
        ports:
          - "8081:8081"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.3

    - name: Create Apache-PHP 7.2 Container-2
      docker_container:
        name: apache2
        image: php:7.2-apache
        state: started
        ports:
          - "8082:8082"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.4

    - name: Copy configs to containers
      command: docker cp {{ folder_structure.path }}/nginx/conf/nginx.conf {{ item }}:/etc/nginx/conf.d
      with_items:
        - nginx
        - apache1
        - apache2

    - name: Bind log paths from container to server
      command: docker run --rm --volumes-from {{ item }} -v {{ folder_structure.path }}/{{ item }}/logs:/logs ubuntu tar cvf /logs/{{ item }}.tar /var/log/{{ item }}
      with_items:
        - nginx
        - apache1
        - apache2

    - name: Restart Nginx Container
      docker_container:
        name: nginx
        image: admintuts/nginx:1.21.4-rtmp-geoip2-alpine
        state: restarted
        ports:
          - "80:80"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.2

    - name: Restart Apache-PHP 7.2 Container-1
      docker_container:
        name: apache1
        image: php:7.2-apache
        state: restarted
        ports:
          - "8081:8081"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.3

    - name: Restart Apache-PHP 7.2 Container-2
      docker_container:
        name: apache2
        image: php:7.2-apache
        state: restarted
        ports:
          - "8082:8082"
        networks:
          - name: custom_network
            ipv4_address: 10.0.0.4
