  - name: Install Node Exporter Docker Container
    hosts: localhost
    become: true
    tasks:
      - name: Pull Node Exporter Docker Image
        docker_image:
          name: prom/node-exporter
          source: pull
          state: present

      - name: Create Node Exporter Container
        docker_container:
          name: node-exporter
          image: prom/node-exporter
          state: started
          networks:
            - name: custom_network
              ipv4_address: 10.0.0.7
          volumes:
            - "/proc:/host/proc"
            - "/sys:/host/sys"
            - "/:/rootfs"

  - name: Install Prometheus, Grafana, and Cadvisor Docker Containers
    hosts: localhost
    become: true
    tasks:
      - name: Pull Prometheus Docker Image
        docker_image:
          name: prom/prometheus
          source: pull
          state: present

      - name: Pull Grafana Docker Image
        docker_image:
          name: grafana/grafana
          source: pull
          state: present

      - name: Pull Cadvisor Docker Image
        docker_image:
          name: google/cadvisor
          source: pull
          state: present


    - name: Copying Prometheus config
      copy:
        src: prometheus.yml
        dest: "/srv/prometheus/conf/prometheus.yml"

      - name: Create Prometheus Container
        docker_container:
          name: prometheus
          image: prom/prometheus
          state: started
          networks:
            - name: custom_network
              ipv4_address: 10.0.0.8
          volumes:
            - "/srv/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml"

      - name: Create Grafana Container
        docker_container:
          name: grafana
          image: grafana/grafana
          state: started
          ports:
            - "3000:3000"
          networks:
            - name: custom_network
              ipv4_address: 10.0.0.9

      - name: Create Cadvisor Container
        docker_container:
          name: cadvisor
          image: google/cadvisor
          state: started
          networks:
            - name: custom_network
              ipv4_address: 10.0.0.10
          volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"