global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.0.0.9:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.0.0.12:8080']

  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.0.0.5:9113']

  - job_name: 'mysql-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.8:9104']
