---
- name: Pull Grafana Docker Image
  docker_image:
    name: grafana/grafana
    source: pull
    state: present

- name: Create Grafana Container
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    networks:
      - name: custom_network
        ipv4_address: 10.0.0.11
    volumes:
      - "/srv/grafana/:/tmp/"
    
#- name: Copy Grafana config to grafana container
#  command: docker cp ./roles/grafana-install/defaults/grafana.ini grafana:/etc/grafana/
    
#- name: Copy Grafana db to grafana container
#  command: docker cp ./roles/grafana-install/defaults/grafana.db grafana:/var/lib/grafana/
