---
- name: Pull Prometheus Mysql exporter Docker Image
  docker_image:
    name: prom/mysqld-exporter
    source: pull
    state: present

- name: Install Prometheus Mysql exporter
  docker_container:
    name: prometheus-mysql-exporter
    image: prom/mysqld-exporter
    state: started
    restart_policy: always
    ports:
      - "9104:9104"
    networks:
      - name: custom_network
        ipv4_address: "{{ prometheus-mysql-exporter_ip }}"
    env:
      DATA_SOURCE_NAME: "root:very_secret@tcp(mysql:3306)/"
