---
- name: Pull Node Exporter Docker Image
  docker_image:
    name: prom/node-exporter
    source: pull
    state: present

- name: Create Node Exporter Container
  docker_container:
    name: node-exporter
    image: prom/node-exporter
    state: started
    restart_policy: always
    networks:
      - name: custom_network
        ipv4_address: "{{ node-exporter_ip }}"
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
