---
- name: Write domains to /etc/hosts
  tasks:
   - name: Configure /etc/hosts
     lineinfile:
       dest: /etc/hosts
       line: "{{ item.ip }} {{ item.hostname }}"
       state: present
     with_items: "{{ domains }}"
