---
- name: Pull Cadvisor Docker Image
  docker_image:
    name: gcr.io/cadvisor/cadvisor:v0.46.0
    source: pull
    state: present

- name: Create Cadvisor Container
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    state: started
    networks:
      - name: custom_network
        ipv4_address: 10.0.0.12
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"